/*
 * Myra EU Captcha API
 * The API for Myra EU CAPTCHA provides one end point to verify the validity of client requests using EU CAPTCHA technology developed by Myra Security.      This API only describes how the validation of the EU CAPTCHA works. For a description of How-To-Integrate the EU CAPTCHA into your website, please refer to https://docs.eu-captcha.eu/         **Version History** | Version | |  Reason for change | | --- | --- | --- | | 1.0 |  | Initial release | 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myrasec.client.api;

import com.myrasec.client.model.VerifyRequest;
import com.myrasec.client.model.VerifyResponse;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for EuCaptchaApi
 */
@Disabled
public class EuCaptchaApiTest {

    private final EuCaptchaApi api = new EuCaptchaApi();

    
    /**
     * Verify submitted client token
     *
     * The client of the end-user have to make certain calculations as a so-called **proof-of-work** mechanism.   The end point determines whether those calculations have been performed correctly. Also if the token has been used before, among other validation functions.      As a result the body returns a JSON object with the attribute &#x60;&#x60;success&#x60;&#x60; as true or false (boolean). 
     */
    @Test
    public void verifyClientTokenTest()  {
        // uncomment below to test the function
        //VerifyRequest verifyRequest = null;
        //VerifyResponse response = api.verifyClientToken(verifyRequest).block();

        // TODO: test validations
    }
    
}
