/*
 * Myra EU Captcha API
 * The API for Myra EU CAPTCHA provides one end point to verify the validity of client requests using EU CAPTCHA technology developed by Myra Security.      This API only describes how the validation of the EU CAPTCHA works. For a description of How-To-Integrate the EU CAPTCHA into your website, please refer to https://docs.eu-captcha.eu/         **Version History** | Version | |  Reason for change | | --- | --- | --- | | 1.0 |  | Initial release | 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.myrasec.client;

import java.time.Instant;
import java.time.OffsetDateTime;
import java.time.ZonedDateTime;

import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.Module.SetupContext;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-11T13:29:19.732646793+01:00[Europe/Berlin]", comments = "Generator version: 7.18.0")
public class RFC3339JavaTimeModule extends SimpleModule {
    private static final long serialVersionUID = 1L;

    public RFC3339JavaTimeModule() {
        super("RFC3339JavaTimeModule");
    }

   @Override
   public void setupModule(SetupContext context) {
       super.setupModule(context);

       addDeserializer(Instant.class, RFC3339InstantDeserializer.INSTANT);
       addDeserializer(OffsetDateTime.class, RFC3339InstantDeserializer.OFFSET_DATE_TIME);
       addDeserializer(ZonedDateTime.class, RFC3339InstantDeserializer.ZONED_DATE_TIME);
   }

}
