/*
 * Myra EU Captcha API
 * The API for Myra EU CAPTCHA provides one end point to verify the validity of client requests using EU CAPTCHA technology developed by Myra Security.      This API only describes how the validation of the EU CAPTCHA works. For a description of How-To-Integrate the EU CAPTCHA into your website, please refer to https://docs.eu-captcha.eu/         **Version History** | Version | |  Reason for change | | --- | --- | --- | | 1.0 |  | Initial release | 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myrasec.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VerifyRequest
 */
class VerifyRequestTest {
    private final VerifyRequest model = new VerifyRequest();

    /**
     * Model tests for VerifyRequest
     */
    @Test
    void testVerifyRequest() {
        // TODO: test VerifyRequest
    }

    /**
     * Test the property 'sitekey'
     */
    @Test
    void sitekeyTest() {
        // TODO: test sitekey
    }

    /**
     * Test the property 'secret'
     */
    @Test
    void secretTest() {
        // TODO: test secret
    }

    /**
     * Test the property 'clientIp'
     */
    @Test
    void clientIpTest() {
        // TODO: test clientIp
    }

    /**
     * Test the property 'clientToken'
     */
    @Test
    void clientTokenTest() {
        // TODO: test clientToken
    }

    /**
     * Test the property 'clientUserAgent'
     */
    @Test
    void clientUserAgentTest() {
        // TODO: test clientUserAgent
    }

}
