/*
 * Myra EU Captcha API
 * The API for Myra EU CAPTCHA provides one end point to verify the validity of client requests using EU CAPTCHA technology developed by Myra Security.  This API only describes how the validation of the EU CAPTCHA works. For a description of How-To-Integrate the EU CAPTCHA into your website, please refer to https://docs.eu-captcha.eu/  <br>  **Version History** | Version | |  Reason for change | | --- | --- | --- | | 1.0 |  | Initial release | 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myrasec.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifyResponse
 */
@JsonPropertyOrder({
  VerifyResponse.JSON_PROPERTY_SUCCESS,
  VerifyResponse.JSON_PROPERTY_TRAIN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-11T09:46:29.202252407+01:00[Europe/Berlin]", comments = "Generator version: 7.18.0")
public class VerifyResponse {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  @javax.annotation.Nullable
  private Boolean success;

  public static final String JSON_PROPERTY_TRAIN = "train";
  @javax.annotation.Nullable
  private Boolean train;

  public VerifyResponse() {
  }

  public VerifyResponse success(@javax.annotation.Nullable Boolean success) {
    
    this.success = success;
    return this;
  }

  /**
   * The status of the verification.  Possible values:&lt;ul&gt;&lt;li&gt;true&lt;/li&gt;&lt;li&gt;false&lt;/li&gt;&lt;/ul&gt; 
   * @return success
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUCCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(value = JSON_PROPERTY_SUCCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(@javax.annotation.Nullable Boolean success) {
    this.success = success;
  }

  public VerifyResponse train(@javax.annotation.Nullable Boolean train) {
    
    this.train = train;
    return this;
  }

  /**
   * If null or false, actual validation was performed.  If true, the field success will always be true. This happens, for example, if the sitekey does not exist, if the secret is incorrect, if the sitekey is set to train&#x3D;true, or some other condition prevents the server to perform the operation. 
   * @return train
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrain() {
    return train;
  }


  @JsonProperty(value = JSON_PROPERTY_TRAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrain(@javax.annotation.Nullable Boolean train) {
    this.train = train;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyResponse verifyResponse = (VerifyResponse) o;
    return Objects.equals(this.success, verifyResponse.success) &&
        Objects.equals(this.train, verifyResponse.train);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, train);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyResponse {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    train: ").append(toIndentedString(train)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

