/*
 * Myra EU Captcha API
 * The API for Myra EU CAPTCHA provides one end point to verify the validity of client requests using EU CAPTCHA technology developed by Myra Security.      This API only describes how the validation of the EU CAPTCHA works. For a description of How-To-Integrate the EU CAPTCHA into your website, please refer to https://docs.eu-captcha.eu/         **Version History** | Version | |  Reason for change | | --- | --- | --- | | 1.0 |  | Initial release |
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myrasec.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifyResponse
 */
@JsonPropertyOrder({
  VerifyResponse.JSON_PROPERTY_SUCCESS,
  VerifyResponse.JSON_PROPERTY_TRAIN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-11T13:29:20.626503746+01:00[Europe/Berlin]", comments = "Generator version: 7.18.0")
public class VerifyResponse {
  public static final String JSON_PROPERTY_SUCCESS = "success";
  @javax.annotation.Nullable
  private Boolean success;

  public static final String JSON_PROPERTY_TRAIN = "train";
  @javax.annotation.Nullable
  private Boolean train;

  public VerifyResponse() {
  }

  public VerifyResponse success(@javax.annotation.Nullable Boolean success) {

    this.success = success;
    return this;
  }

  /**
   * The status of the verification.      Possible values:       - true     - false
   * @return success
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUCCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(value = JSON_PROPERTY_SUCCESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(@javax.annotation.Nullable Boolean success) {
    this.success = success;
  }

  public VerifyResponse train(@javax.annotation.Nullable Boolean train) {

    this.train = train;
    return this;
  }

  /**
   * Indicates whether the response was produced in training (shadow) mode rather than real validation.
   * <p>
   * When {@code true}, the {@code success} field is always {@code true} regardless of the actual
   * CAPTCHA result. This occurs when:
   * <ul>
   *   <li>The sitekey does not exist</li>
   *   <li>The secret is incorrect</li>
   *   <li>The sitekey is configured with {@code train=true}</li>
   *   <li>Some other condition prevents the server from performing real validation</li>
   * </ul>
   * When {@code null} or {@code false}, real validation was performed and {@code success} reflects
   * the actual result. <strong>Do not rely on {@code success} for access control when this field
   * is {@code true}.</strong>
   *
   * @return {@code true} if training mode was active, {@code false} or {@code null} otherwise
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TRAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTrain() {
    return train;
  }


  @JsonProperty(value = JSON_PROPERTY_TRAIN, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTrain(@javax.annotation.Nullable Boolean train) {
    this.train = train;
  }

  /**
   * Returns {@code true} if this response was produced in training mode.
   * Safe to call even when {@link #getTrain()} returns {@code null}.
   *
   * @return {@code true} if training mode was active
   * @see #getTrain()
   */
  public boolean isTrainingMode() {
    return Boolean.TRUE.equals(train);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyResponse verifyResponse = (VerifyResponse) o;
    return Objects.equals(this.success, verifyResponse.success) &&
        Objects.equals(this.train, verifyResponse.train);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, train);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyResponse {\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    train: ").append(toIndentedString(train)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

