/*
 * Myra EU Captcha API
 * The API for Myra EU CAPTCHA provides one end point to verify the validity of client requests using EU CAPTCHA technology developed by Myra Security.  This API only describes how the validation of the EU CAPTCHA works. For a description of How-To-Integrate the EU CAPTCHA into your website, please refer to https://docs.eu-captcha.eu/  <br>  **Version History** | Version | |  Reason for change | | --- | --- | --- | | 1.0 |  | Initial release | 
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myrasec.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VerifyRequest
 */
@JsonPropertyOrder({
  VerifyRequest.JSON_PROPERTY_SITEKEY,
  VerifyRequest.JSON_PROPERTY_SECRET,
  VerifyRequest.JSON_PROPERTY_CLIENT_IP,
  VerifyRequest.JSON_PROPERTY_CLIENT_TOKEN,
  VerifyRequest.JSON_PROPERTY_CLIENT_USER_AGENT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-02-11T09:46:28.304865520+01:00[Europe/Berlin]", comments = "Generator version: 7.18.0")
public class VerifyRequest {
  public static final String JSON_PROPERTY_SITEKEY = "sitekey";
  @javax.annotation.Nonnull
  private String sitekey;

  public static final String JSON_PROPERTY_SECRET = "secret";
  @javax.annotation.Nonnull
  private String secret;

  public static final String JSON_PROPERTY_CLIENT_IP = "client_ip";
  @javax.annotation.Nonnull
  private String clientIp;

  public static final String JSON_PROPERTY_CLIENT_TOKEN = "client_token";
  @javax.annotation.Nonnull
  private String clientToken;

  public static final String JSON_PROPERTY_CLIENT_USER_AGENT = "client_user_agent";
  @javax.annotation.Nonnull
  private String clientUserAgent;

  public VerifyRequest() {
  }

  public VerifyRequest sitekey(@javax.annotation.Nonnull String sitekey) {
    
    this.sitekey = sitekey;
    return this;
  }

  /**
   * The public site key associated with the domain.  The public site key can be found in your account on the EU CAPTCHA website under **Dashboard** view -&gt; **Site Key List** area -&gt; **Settings** button -&gt; **Details** tab.  &lt;br&gt;  &gt;&gt; --- &gt;&gt; Example: &gt;&gt; &#x60;&#x60;1c87e240-.....-23ac9f99da68&#x60;&#x60; &gt;&gt; --- 
   * @return sitekey
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SITEKEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSitekey() {
    return sitekey;
  }


  @JsonProperty(value = JSON_PROPERTY_SITEKEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSitekey(@javax.annotation.Nonnull String sitekey) {
    this.sitekey = sitekey;
  }

  public VerifyRequest secret(@javax.annotation.Nonnull String secret) {
    
    this.secret = secret;
    return this;
  }

  /**
   * The secret key associated with the site key (non-public information).  The secret key can be found in your account on the EU CAPTCHA website under **Dashboard** view -&gt; **Site Key List** area -&gt; **Settings** button -&gt; **Details** tab.  &lt;br&gt;  &gt;&gt; --- &gt;&gt; Example: &gt;&gt; &#x60;&#x60;LqFgQA+.....wdjvI&#x3D;&#x60;&#x60; &gt;&gt; --- 
   * @return secret
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SECRET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSecret() {
    return secret;
  }


  @JsonProperty(value = JSON_PROPERTY_SECRET, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecret(@javax.annotation.Nonnull String secret) {
    this.secret = secret;
  }

  public VerifyRequest clientIp(@javax.annotation.Nonnull String clientIp) {
    
    this.clientIp = clientIp;
    return this;
  }

  /**
   * The IPv4 or IPv6 address of the client submitting the token.  &lt;br&gt;  &gt;&gt; --- &gt;&gt; Example: &gt;&gt; &#x60;&#x60;5.6.7.8&#x60;&#x60; &gt;&gt; ---  &lt;br&gt;  &gt;&gt; --- &gt;&gt; Note: &gt;&gt; Make sure to submit the actual IP address of the client, and not the IP address of your CDN (e.g. by using X-Client-CDN or X-Forwarded-For where appropriate). &gt;&gt; --- 
   * @return clientIp
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CLIENT_IP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientIp() {
    return clientIp;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_IP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientIp(@javax.annotation.Nonnull String clientIp) {
    this.clientIp = clientIp;
  }

  public VerifyRequest clientToken(@javax.annotation.Nonnull String clientToken) {
    
    this.clientToken = clientToken;
    return this;
  }

  /**
   * The token generated by &#x60;&#x60;verify.js&#x60;&#x60;, usually submitted to the server as a POST field called \&quot;eu-captcha-response\&quot;. This can also be an empty string.  &lt;br&gt;  &gt;&gt; --- &gt;&gt; Example: &gt;&gt; &#x60;&#x60;XVtHUQ.....UF9ESkQUAxUTChJEXFFVX1ZXURs&#x3D;&#x60;&#x60; &gt;&gt; ---   &lt;br&gt;  &gt;&gt; --- &gt;&gt; Note: &gt;&gt; Always submit the data to the API end point to ensure that the captcha mechanism receives information about all captcha users, especially the broken ones. &gt;&gt; --- 
   * @return clientToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CLIENT_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientToken() {
    return clientToken;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientToken(@javax.annotation.Nonnull String clientToken) {
    this.clientToken = clientToken;
  }

  public VerifyRequest clientUserAgent(@javax.annotation.Nonnull String clientUserAgent) {
    
    this.clientUserAgent = clientUserAgent;
    return this;
  }

  /**
   * The user-agent request header of the client. In case the token was not computed, this helps us identify what kind of client tried to access your service.  &lt;br&gt;  &gt;&gt; --- &gt;&gt; Example: &gt;&gt; &#x60;&#x60;Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/531.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/531.36&#x60;&#x60; &gt;&gt; ---  &lt;br&gt; 
   * @return clientUserAgent
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CLIENT_USER_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getClientUserAgent() {
    return clientUserAgent;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_USER_AGENT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientUserAgent(@javax.annotation.Nonnull String clientUserAgent) {
    this.clientUserAgent = clientUserAgent;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyRequest verifyRequest = (VerifyRequest) o;
    return Objects.equals(this.sitekey, verifyRequest.sitekey) &&
        Objects.equals(this.secret, verifyRequest.secret) &&
        Objects.equals(this.clientIp, verifyRequest.clientIp) &&
        Objects.equals(this.clientToken, verifyRequest.clientToken) &&
        Objects.equals(this.clientUserAgent, verifyRequest.clientUserAgent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sitekey, secret, clientIp, clientToken, clientUserAgent);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyRequest {\n");
    sb.append("    sitekey: ").append(toIndentedString(sitekey)).append("\n");
    sb.append("    secret: ").append(toIndentedString(secret)).append("\n");
    sb.append("    clientIp: ").append(toIndentedString(clientIp)).append("\n");
    sb.append("    clientToken: ").append(toIndentedString(clientToken)).append("\n");
    sb.append("    clientUserAgent: ").append(toIndentedString(clientUserAgent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

